### ISSUE TITLE
Invalid spark download link in Dockerfile

### ISSUE THREAD

**Issue by vminfant** [spatialx-project/docker-spark-geolake#1]
This is indeed very interesting project! thank you for making it public! 

I just realised that the spark download link seems to be wrongly populated in `Dockerfile`.  Please update it when you find time or highlight if i can make a PR. Thanks! 

Incorrect. 
```shell
# Download spark
RUN curl https://dlcdn.apache.org/spark/spark-3.3.1/spark-3.3.1-bin-hadoop3.tgz -o spark-3.3.1-bin-hadoop3.tgz \
 && tar xvzf spark-3.3.1-bin-hadoop3.tgz --directory /opt/spark --strip-components 1 \
 && rm -rf spark-3.3.1-bin-hadoop3.tgz
```

Correct. 
```shell
# Download spark
RUN curl https://archive.apache.org/dist/spark/spark-3.3.1/spark-3.3.1-bin-hadoop3.tgz -o spark-3.3.1-bin-hadoop3.tgz \
 && tar xvzf spark-3.3.1-bin-hadoop3.tgz --directory /opt/spark --strip-components 1 \
 && rm -rf spark-3.3.1-bin-hadoop3.tgz
```

Also, Jupyter notebook doesnt show any token.

**Comment by badbye** [comment]
@vminfant  The link has been updated, thanks.

> Also, Jupyter notebook doesnt show any token.

I have no idea what is going on, can you provide more information?
