### ISSUE TITLE
default memory settings too low for benchmark

### ISSUE THREAD

**Issue by ttomasz** [spatialx-project/docker-spark-geolake#2]
I tried to run notebook with benchmark but was getting messages about java heap out of memory.

I found that one could set spark parameters from the notebook using:
```
%%init_spark
launcher.num_executors = 1
launcher.executor_cores = 8
launcher.driver_memory = '16g'
launcher.executor_memory = '16g'
launcher.conf.set("spark.driver.maxResultSize","4g")
```
I would suggest adding that and some comment to the notebook.

**Comment by badbye** [comment]
Good suggestion. I've added it to the notebook.

For someone who does not have enough memory, I've also provided a solution: split the file and only read the first N records.
