### ISSUE TITLE
portotaxi.geojson Unexpected end-of-input: expected close marker for Object

### ISSUE THREAD

**Issue by ttomasz** [spatialx-project/docker-spark-geolake#3]
In benchmark notebook on the cell with:
```scala
val fullFile = "/home/iceberg/data/portotaxi2.geojson"
val df = readGeojson(fullFile).repartition(50)
df.cache
df.createOrReplaceTempView("portotaxi")
```
I am getting the following error:
```
java.lang.RuntimeException: com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input: expected close marker for Object (start marker at [Source: (String)"{"; line: 1, column: 1])
 at [Source: (String)"{"; line: 1, column: 2]
  at org.wololo.geojson.GeoJSONFactory.create(GeoJSONFactory.java:31)
  at readGeojson(<console>:34)
  ... 40 elided
Caused by: com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input: expected close marker for Object (start marker at [Source: (String)"{"; line: 1, column: 1])
 at [Source: (String)"{"; line: 1, column: 2]
  at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:682)
  at com.fasterxml.jackson.core.base.ParserBase._handleEOF(ParserBase.java:494)
  at com.fasterxml.jackson.core.base.ParserBase._eofAsNextChar(ParserBase.java:511)
  at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipWSOrEnd(ReaderBasedJsonParser.java:2443)
  at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:935)
  at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer._deserializeContainerNoRecursion(JsonNodeDeserializer.java:437)
  at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:84)
  at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:20)
  at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
  at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4716)
  at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3076)
  at org.wololo.geojson.GeoJSONFactory.create(GeoJSONFactory.java:21)
  ... 41 more
```
I'll try downloading the file outside of docker and try to open it in qgis but `tail` on the file look more or less normal. Not sure if there is another way to validate if the file was correctly downloaded?

I got the file by running:
`wget https://star.cs.ucr.edu/datasets/portotaxi/download.geojson.gz -O - | gzip -d > /home/iceberg/data/portotaxi.geojson`
in jupyter terminal.
Btw maybe it would be possible to use some jupyter cell magic commands to run it from notebook?

**Comment by badbye** [comment]
My bad. The file should be cleaned before reading, here is an updated `readGeojson` function, you can paste to your notebook: 

```scala
def readGeojson(filePath: String): DataFrame = {
    val colnames = Seq("TRIP_ID", "CALL_TYPE", "ORIGIN_STAND", "TAXI_ID", "TIMESTAMP", "DAY_TYPE", "MISSING_DATA",  "geometry")
    val geoJsonString = spark.read.textFile(filePath).collect().mkString
    val mapper = new ObjectMapper()
    val it = mapper.readTree(geoJsonString).get("features").iterator()
    var features = Seq[Feature]()
    while (it.hasNext()) {
        val nextFea = it.next()
        try {
            features = features :+ GeoJSONFactory.create(nextFea.toString).asInstanceOf[Feature]
        } catch {
             case e: Exception => null
        }
    }
    val rows = features.map(feature => {
        val reader = new GeoJSONReader
        (
    		feature.getProperties.get("TRIP_ID").asInstanceOf[Long]
          	,feature.getProperties.get("CALL_TYPE").asInstanceOf[String]
    		,feature.getProperties.get("ORIGIN_STAND").asInstanceOf[String]
    		,feature.getProperties.get("TAXI_ID").asInstanceOf[Integer]
    		,feature.getProperties.get("TIMESTAMP").asInstanceOf[String]
    		,feature.getProperties.get("DAY_TYPE").asInstanceOf[String]
    		,feature.getProperties.get("MISSING_DATA").asInstanceOf[Boolean]
    		,reader.read(feature.getGeometry)
    	)
    })
    sc.parallelize(rows).toDF(colnames: _*)
}
```

The notebook is also [updated](https://github.com/spatialx-project/docker-spark-geolake/blob/main/notebooks/benchmark-portotaxi.ipynb), you can use this one directly.

**Comment by ttomasz** [comment]
I am getting OutOfMemory error on: `val geoJsonString = spark.read.textFile(filePath).collect().mkString`
maybe there is a better way to read the file so it doesn't need to be materialized as string in driver's memory?

```scala
import org.apache.sedona.core.formatMapper.GeoJsonReader

val geojson = GeoJsonReader.readToGeometryRDD(spark.sqlContext.sparkContext, "/home/iceberg/data/portotaxi.geojson")
```
gets Sedona SpatialRDD but I didn't have time yet to check how to convert that to DataFrame.

**Comment by ttomasz** [comment]
Ok so after taking a look at it:
- `GeoJsonReader.readToGeometryRDD` expects file with line delimited geojson documents
- portotaxi.geojson contains one huge multiline geojson

I tried reading it with spark's default reader using the following:
```scala
val data = spark.read.option("multiline", true).json("/home/iceberg/data/portotaxi.geojson")
data.select(explode($"features") as "exploded").select("exploded.*").show()
```
But since there is single root component with all the data (`features` array) spark tries to first load it into single column but that is impossible due to [hard limit of 2GB per column value](https://stackoverflow.com/questions/69928983/how-to-overcome-the-2gb-limit-for-a-single-column-value-in-spark) (file is 3,5GB).

I thought about converting the multiline geojson to line delimited so I wrote this script: https://gist.github.com/ttomasz/661d5ec910744cb778c222a949413b6d This could also be done using Jackson in Scala but I'm less familiar with it and anyway on uncompressed geojson it takes 2,5 minutes to convert without loading the full file into memory.

With that I wanted to read the file using Sedone as mentioned above with the following code:
```scala
import org.apache.sedona.core.formatMapper.GeoJsonReader
import org.apache.sedona.sql.utils.Adapter

val spatialRDD = GeoJsonReader.readToGeometryRDD(spark.sqlContext.sparkContext, "/home/iceberg/data/portotaxi.geojsonl")
val df = Adapter.toDf(spatialRDD, spark)
```
But encountered two issues:
1. Sedona splits multipoints into points 
2. On full file I am getting NullPointerException

I tried validating each record during conversion using: https://pypi.org/project/geojson/ but it says all rows are valid.

I posted to their discord with questions about [1](https://discord.com/channels/1034906732264181760/1086958039384469614) and [2](https://discord.com/channels/1034906732264181760/1086958987519475732).

**Comment by ttomasz** [comment]
This looks like it might work:
```scala
import org.apache.spark.sql.types._

val schema = new StructType()
    .add("geometry", StringType)
    .add("properties", new StructType()
        .add("CALL_TYPE", StringType)
        .add("DAY_TYPE", StringType)
        .add("MISSING_DATA", BooleanType)
        .add("ORIGIN_CALL", StringType)
        .add("ORIGIN_STAND", StringType)
        .add("TAXI_ID", LongType)
        .add("TIMESTAMP", StringType)
        .add("TRIP_ID", LongType)
    )
    .add("type", StringType)

spark
.read
.schema(schema)
.json("/home/iceberg/data/portotaxi.geojsonl")
.selectExpr("properties.*", "ST_GeomFromGeoJSON(geometry) as geom")
.show()
```

So maybe it's just Sedona issue with the problems in previous comment.

**Comment by badbye** [comment]
> On full file I am getting NullPointerException

Probably because there are some records that do not have the `geometry` property. Actually, the file is not a valid geojson file, according to the [GeoJson spec](https://geojson.org/geojson-spec#feature-objects): `A feature object must have a member with the name "geometry"`.

**Comment by badbye** [comment]
> This looks like it might work:
> 
> ```scala
> import org.apache.spark.sql.types._
> 
> val schema = new StructType()
>     .add("geometry", StringType)
>     .add("properties", new StructType()
>         .add("CALL_TYPE", StringType)
>         .add("DAY_TYPE", StringType)
>         .add("MISSING_DATA", BooleanType)
>         .add("ORIGIN_CALL", StringType)
>         .add("ORIGIN_STAND", StringType)
>         .add("TAXI_ID", LongType)
>         .add("TIMESTAMP", StringType)
>         .add("TRIP_ID", LongType)
>     )
>     .add("type", StringType)
> 
> spark
> .read
> .schema(schema)
> .json("/home/iceberg/data/portotaxi.geojsonl")
> .selectExpr("properties.*", "ST_GeomFromGeoJSON(geometry) as geom")
> .show()
> ```
> 
> So maybe it's just Sedona issue with the problems in previous comment.

This is indeed a much better solution. Would you like to submit a merge request?

**Comment by ttomasz** [comment]
I'll try if I mange to find enough time
